version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: spondy-postgres-frontend-dev
    environment:
      POSTGRES_DB: spondy_club
      POSTGRES_USER: spondy
      POSTGRES_PASSWORD: spondy123
    ports:
      - "5432:5432"
    volumes:
      - postgres_frontend_dev_data:/var/lib/postgresql/data
    networks:
      - spondy-frontend-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spondy -d spondy_club"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  spondy-frontend-dev-network:
    driver: bridge

volumes:
  postgres_frontend_dev_data: 