version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: spondy-postgres-dev
    environment:
      POSTGRES_DB: spondy_club
      POSTGRES_USER: spondy
      POSTGRES_PASSWORD: spondy123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - spondy-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spondy -d spondy_club"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spondy-backend-dev
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - spondy-dev-network
    volumes:
      # Mount source code for hot reload (if using Spring Boot DevTools)
      - ./backend/src:/app/src:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  spondy-dev-network:
    driver: bridge

volumes:
  postgres_dev_data: 