version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: spondy-postgres
    environment:
      POSTGRES_DB: spondy_club
      POSTGRES_USER: spondy
      POSTGRES_PASSWORD: spondy123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spondy-network

networks:
  spondy-network:
    driver: bridge

volumes:
  postgres_data: 