spring:
  application:
    name: spond-club-membership
  
  datasource:
    url: jdbc:h2:mem:spondy_club
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  web:
    cors:
      allowed-origins: "http://localhost:5173,http://localhost:5174"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

server:
  port: 8080

logging:
  level:
    no.spond.club: DEBUG
    org.springframework.web: DEBUG 