spring:
  application:
    name: spond-club-membership
  
  datasource:
    url: jdbc:postgresql://localhost:5432/spondy_club
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    no.spond.club: DEBUG
