spring:
  application:
    name: spond-club-membership
  
  datasource:
    url: jdbc:postgresql://postgres:5432/spondy_club
    driver-class-name: org.postgresql.Driver
    username: spondy
    password: spondy123
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    no.spond.club: DEBUG
    org.springframework.web: DEBUG 